<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bolius_geocodedk"
 *
 * Auto generated by Extension Builder 2013-10-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bolius Geocode Denmark',
	'description' => 'Provides a fast geocoding of coordinates in Denmark.

Supplies accuracy at zip code level.',
	'category' => 'plugin',
	'author' => 'Bolius Online',
	'author_email' => 'egi@bolius.dk',
	'author_company' => 'Bolius',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
            'typo3' => '6.2',
			'bolius_geoip' => '1.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
